### ISSUE TITLE
Incompatible with recent pip versions

### ISSUE THREAD

**Issue by jachymb** [danielnyga/pracmln#23]
Trying to run 

    python setup.py

with recent versions of pip (I am using pip 18, but I believe the problem is with any version >= 10) I am getting the following error:

    Traceback (most recent call last):
      File "setup.py", line 7, in <module>
        pip.main(['install', 'appdirs'])
    AttributeError: module 'pip' has no attribute 'main'

**Comment by jachymb** [comment]
Note: A similar error message is shown when running `pip install pracmln`

**Comment by kaivalyar** [comment]
This issue was resolved in PR #19. However, that PR has not been merged yet.

You can downlaod the pracmln source, and apply the changes yourself to fix this error for your local computer. Please revert back on this thread if this doesn't work.

**Comment by SymonJoryStevens-Guille** [comment]
Pip no longer provides direct access to main; it has to be fetched from pip_internal. 

The fix in PR #19 works, but still requires using `main`. Also, it requires a manual install, rather than install via Pip, since the fetched package on pip does not have the workaround merged into it. I am under the impression that similar results can be achieved with 'subprocess', which is what the pip documentation reccomends:

`import subprocess`
`subprocess.check_call(["python", '-m', 'pip', 'install', 'appdirs'])`

Just dropping this in won't do the trick though, since it appears to introduce some dependency issues with distutils. For instance, I got an error thrown from the conjunction of the code above and the invocation of:

 `distutils.command.install.install`

I'm sure there's a simple workaround for this, but I haven't spent enough time thinking about it.

**Comment by danielnyga** [comment]
Fixed in release 1.2.4.
