### ISSUE TITLE
MLN not learning with network defined using python API

### ISSUE THREAD

**Issue by MdAsifKhan** [danielnyga/pracmln#6]
Hey,
I defined a MLN network using python API but there seems to be some issues in using this network for learning. Weight of one of the rule is always zero. However, when I define the same network in text file and save it as '.mln' file it works fine.
Is there any issue with python API?. This is how I defined a simple MLN:
`mln = MLN(grammar='PRACGrammar',logic='FirstOrderLogic')
# MLN for smoking Network

# Predicate Declaration
mln << 'Friends(person, person)'
mln << 'Smokes(person)'
mln << 'Cancer(person)'
# Rules
# If you smoke, you get cancer
mln << 'Smokes(x) => Cancer(x).'
# People with friends who smoke, also smoke  and those with friends who don't smoke, don't smoke
mln << 'Friends(x, y) => (Smokes(x) <=> Smokes(y)).'
mln.weights = ['0','0']
mln.write()`

**Comment by danielnyga** [comment]
Hi,
please note that when you append a period (".") at the end of a formula, this formula will be treated as a hard formula with infinite weight, so it will not be subject to learning. Directly setting the weights with `mln.weights` afterwards breaks this semantics and is highly discouraged. If you want to specify weighted formulae, you have to provide a weight that precedes the formula. Furthermore, you selected the PRACGrammar in your MLN specification. When using the PRACGrammar, variables must be preceded by a question mark ("?") to indicate that the subsequent symbol is a variable. Otherwise, it's treated as a constant, which might explain why your formulae have 0 weight after learning. I.e. in your example:
```
mln << '0 Smokes(?x) => Cancer(?x)'
mln << '0 Friends(?x, ?y) => (Smokes(?x) <=> Smokes(?y))'
```
is the right way to specify the model. Please remember also that the result of the learning in MLNs very strongly depends on your training data and the learning algorithm you choose. If you need a more detailed error analysis, you have to provide your training databases and algorithm settings. I hope this helps for now. 

-d.

**Comment by MdAsifKhan** [comment]
Hey,
Thanks for the detailed answer. It works now. Earlier I also tried with weights preceding rule. But then I got some ValueError and I messed few things. Thanks for mentioning about grammar:)
